import { promises as fs } from "node:fs";
import path from "node:path";
import { createHash, timingSafeEqual } from "node:crypto";
import { cookies } from "next/headers";

export const AUTH_COOKIE = "dash-auth";

function hashPassword(pw: string): string {
  return createHash("sha256").update(pw).digest("hex");
}

export function getExpectedAuthHash(): string | null {
  const pw = process.env.DASHBOARD_PASSWORD;
  if (!pw) return null;
  return hashPassword(pw);
}

export function checkAuthHash(provided: string): boolean {
  const expected = getExpectedAuthHash();
  if (!expected) return false;
  if (provided.length !== expected.length) return false;
  return timingSafeEqual(Buffer.from(provided), Buffer.from(expected));
}

export async function isAuthed(): Promise<boolean> {
  const store = await cookies();
  const cookie = store.get(AUTH_COOKIE);
  if (!cookie) return false;
  return checkAuthHash(cookie.value);
}

export function buildAuthCookieValue(password: string): string {
  return hashPassword(password);
}

export type ShowcaseType = "regular" | "special";

export type ShowcaseItem = {
  id: string;
  name: string;
  description: string;
  fileName: string;
  exportName: string;
  registryName: string;
  landscape: boolean;
};

export type Manifest = {
  regular: ShowcaseItem[];
  special: ShowcaseItem[];
};

const ROOT = process.cwd();
const MANIFEST_PATH = path.join(ROOT, "src", "data", "showcase-manifest.json");
const ASCII_DIR = path.join(ROOT, "src", "components", "ascii");
const REGISTRY_PATH = path.join(ASCII_DIR, "_registry.tsx");

export async function readManifest(): Promise<Manifest> {
  const raw = await fs.readFile(MANIFEST_PATH, "utf8");
  return JSON.parse(raw) as Manifest;
}

export async function writeManifest(manifest: Manifest): Promise<void> {
  await fs.writeFile(
    MANIFEST_PATH,
    JSON.stringify(manifest, null, 2) + "\n",
    "utf8",
  );
}

export function slugify(input: string): string {
  return input
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9-\s]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

export function pascalCase(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .split(/[\s-]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("");
}

export function resolveAsciiFilePath(fileName: string): string {
  if (!/^[a-z0-9-]+\.tsx$/i.test(fileName)) {
    throw new Error(`Invalid fileName: ${fileName}`);
  }
  const absolute = path.join(ASCII_DIR, fileName);
  const normalized = path.normalize(absolute);
  if (!normalized.startsWith(ASCII_DIR + path.sep)) {
    throw new Error(`Path traversal blocked: ${fileName}`);
  }
  return normalized;
}

export function validateTsx(content: string, exportName: string): void {
  if (!content.trim()) {
    throw new Error("TSX content is empty");
  }
  const hasDefault = /export\s+default\b/.test(content);
  const hasNamedExport = new RegExp(
    `export\\s+(?:const|function|class)\\s+${exportName}\\b`,
  ).test(content);
  if (!hasDefault && !hasNamedExport) {
    throw new Error(
      `TSX must have a default export, or a named export matching "${exportName}"`,
    );
  }
}

function renderRegular(item: ShowcaseItem): string {
  return `  {
    name: ${JSON.stringify(item.name)},
    description: ${JSON.stringify(item.description)},
    registryName: ${JSON.stringify(item.registryName)},
    landscape: ${item.landscape},
    render: () => <${item.exportName} />,
  },`;
}

function renderSpecial(item: ShowcaseItem): string {
  return `  {
    name: ${JSON.stringify(item.name)},
    description: ${JSON.stringify(item.description)},
    registryName: ${JSON.stringify(item.registryName)},
    landscape: ${item.landscape},
    render: (isPlaying: boolean) => <${item.exportName} isPlaying={isPlaying} />,
  },`;
}

export function buildRegistrySource(manifest: Manifest): string {
  const all = [...manifest.regular, ...manifest.special];
  const seenExports = new Set<string>();
  const imports = all
    .filter((item) => {
      if (seenExports.has(item.exportName)) return false;
      seenExports.add(item.exportName);
      return true;
    })
    .map(
      (item) =>
        `import ${item.exportName} from "./${item.fileName.replace(/\.tsx$/, "")}";`,
    )
    .join("\n");

  const regular = manifest.regular.map(renderRegular).join("\n");
  const special = manifest.special.map(renderSpecial).join("\n");

  return `// AUTO-GENERATED by the studio dashboard — do not edit by hand.
import type { ReactNode } from "react";
${imports}

export type AnimationCard = {
  name: string;
  description: string;
  registryName: string;
  landscape: boolean;
};

export type AnimationItem = AnimationCard & {
  render: () => ReactNode;
};

export type SpecialEffectItem = AnimationCard & {
  render: (isPlaying: boolean) => ReactNode;
};

export const regularAnimations: AnimationItem[] = [
${regular}
];

export const specialEffects: SpecialEffectItem[] = [
${special}
];
`;
}

export async function regenerateRegistry(manifest: Manifest): Promise<void> {
  const source = buildRegistrySource(manifest);
  await fs.writeFile(REGISTRY_PATH, source, "utf8");
}

export async function readAsciiFile(fileName: string): Promise<string> {
  const filePath = resolveAsciiFilePath(fileName);
  return fs.readFile(filePath, "utf8");
}

export async function writeAsciiFile(
  fileName: string,
  content: string,
): Promise<void> {
  const filePath = resolveAsciiFilePath(fileName);
  await fs.writeFile(filePath, content, "utf8");
}

export async function deleteAsciiFile(fileName: string): Promise<void> {
  const filePath = resolveAsciiFilePath(fileName);
  await fs.unlink(filePath);
}

export function findItem(
  manifest: Manifest,
  id: string,
): { item: ShowcaseItem; type: ShowcaseType } | null {
  const reg = manifest.regular.find((i) => i.id === id);
  if (reg) return { item: reg, type: "regular" };
  const spc = manifest.special.find((i) => i.id === id);
  if (spc) return { item: spc, type: "special" };
  return null;
}

export function isIdTaken(manifest: Manifest, id: string): boolean {
  return (
    manifest.regular.some((i) => i.id === id) ||
    manifest.special.some((i) => i.id === id)
  );
}
