// AUTO-GENERATED by the studio dashboard — do not edit by hand.
import type { ReactNode } from "react";
import Train from "./train";
import Car from "./car";
import Skull from "./skull";
import Cd from "./cd";
import RocketBlast from "./rocket-blast";
import Lightning from "./lightning";
import SeaLines from "./sea-lines";
import Pitstop from "./pitstop";
import RedFire from "./red-fire";

export type AnimationCard = {
  name: string;
  description: string;
  registryName: string;
  landscape: boolean;
};

export type AnimationItem = AnimationCard & {
  render: () => ReactNode;
};

export type SpecialEffectItem = AnimationCard & {
  render: (isPlaying: boolean) => ReactNode;
};

export const regularAnimations: AnimationItem[] = [
  {
    name: "train",
    description: "...",
    registryName: "train",
    landscape: true,
    render: () => <Train />,
  },
  {
    name: "car",
    description: "....",
    registryName: "car",
    landscape: true,
    render: () => <Car />,
  },
  {
    name: "Skull",
    description: "ASCII animation of a skull.",
    registryName: "skull",
    landscape: false,
    render: () => <Skull />,
  },
  {
    name: "CD Animation",
    description: "ASCII animation of a CD spinning.",
    registryName: "cd",
    landscape: false,
    render: () => <Cd />,
  },
  {
    name: "Rocket Blast",
    description: "ASCII rocket blasting off with animated flames and smoke.",
    registryName: "rocket-blast-2",
    landscape: true,
    render: () => <RocketBlast />,
  },
  {
    name: "Lightning",
    description: "ASCII animation of a Formula 1 pitstop with cars and crew.",
    registryName: "lightning",
    landscape: false,
    render: () => <Lightning />,
  },
  {
    name: "Sea Lines",
    description: "ASCII animation of a Formula 1 pitstop with cars and crew.",
    registryName: "sea-lines",
    landscape: false,
    render: () => <SeaLines />,
  },
  {
    name: "Pitstop",
    description: "ASCII animation of a Formula 1 pitstop with cars and crew.",
    registryName: "pitstop",
    landscape: true,
    render: () => <Pitstop />,
  },
  {
    name: "Red Fire",
    description: "ASCII flame animation in a red terminal style.",
    registryName: "red-fire",
    landscape: false,
    render: () => <RedFire />,
  },
];

export const specialEffects: SpecialEffectItem[] = [

];
